---
server:
  httpPort: ${HTTP_PORT:-8080}
  metricsPort: ${METRICS_PORT:-8081}
  readHeaderTimeoutSec: ${READ_HEADER_TIMEOUT_SEC:-30}
  gin:
    cors:
      allowOrigins: ${CORS_ALLOW_ORIGINS:-'*'}
      allowMethods: ${CORS_ALLOW_METHODS:-'GET,POST,PUT,DELETE,OPTIONS'}
      allowHeaders: ${CORS_ALLOW_HEADERS:-'Content-Type'}
    log:
      accessLog: ${GIN_LOG_ACCESS_LOG:-true}
      accessLogRequestBody: ${GIN_LOG_ACCESS_LOG_REQUEST_BODY:-false}
      accessLogResponseBody: ${GIN_LOG_ACCESS_LOG_RESPONSE_BODY:-false}
    debug:
      gin: ${GIN_DEBUG_GIN:-false}
      wait: ${GIN_DEBUG_WAIT:-false}
  shutdown:
    timeSec1: ${SHUTDOWN_TIME_SEC1:-1}
    timeSec2: ${SHUTDOWN_TIME_SEC2:-1}
db:
  driverName: ${APP_DB_DRIVER_NAME:-mysql}
  mysql:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    host: ${MYSQL_HOST:-127.0.0.1}
    port: ${MYSQL_PORT:-3306}
    database: ${MYSQL_DATABASE:-local}
auth:
  signingKey: ${AUTH_SIGNING_KEY}
  accessTokenTtlMin: ${AUTH_ACCESS_TOKEN_TTL_MIN:-60}
log:
  level: ${LOG_LEVEL:-info}
  exporter: ${LOG_EXPORTER:-none}
  otlp:
    endpoint: ${LOG_OTLP_ENDPOINT:-localhost:4318}
    insecure: ${LOG_OTLP_INSECURE:-true}
  uptrace:
    endpoint: ${LOG_UPTRACE_ENDPOINT:-api.uptrace.dev}
    dsn: ${LOG_UPTRACE_DSN:-dummy}
