---
name: Check Go
on:
  pull_request:
    branches:
      - main
    paths:
      - "backend-gin-gorm/**"
  push:
    branches:
      - main
    paths:
      - "backend-gin-gorm/**"
permissions: {}
jobs:
  golang:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    strategy:
      matrix:
        workdir:
          - backend-gin-gorm
    name: golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.workdir }}/go.mod

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: --config=../.golangci.yml --timeout=10m
          tool_name: golangci-lint
          filter_mode: nofilter
          fail_level: error
          workdir: ${{ matrix.workdir }}
